# This is a basic workflow to help you get started with Actions

name: Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [main]

jobs:
  bulid:
    name: Production
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/ariswap/backend
            git pull
            export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v16.9.0/bin/"
            yarn install
            yarn pm2-restart
